### ISSUE TITLE
Error: Cannot provide critical values see `help(radf_crit)`.

### ISSUE THREAD

**Issue by MislavSag** [kvasilopoulos/exuber#11]
I have just tried radf function n daily stock close price. It returns an error if I call a summary method on output:
`Error: Cannot provide critical values see `help(radf_crit)`.`

Is it because I have more than 600 observations? I have 6.358 observations.
If that is not the reason, I can make repr. example.

Additionally, how should your approach on non-stationary data?

**Comment by kvasilopoulos** [comment]
Well yes, that is the reason. `exuber` provides critical values up to 600, then we have `exuberdata` that has critical values up to 2000.
6.358 is an insane amount of observations. Of course, you can use custom critical values with `cv <- radf_mc_cv(6.358)`, but it will take a lot of time. Then you can use `cv` as the second argument in summary. My advice is to aggregate your data to monthly or weekly frequency --- it will give you more meaningful results.

**Comment by MislavSag** [comment]
I will try to aggregate the data than. I thought higher frequency would give better estimates, but maybe it would just add noise?

**Comment by kvasilopoulos** [comment]
Yes exactly.

**Comment by MislavSag** [comment]
sorry for opening again, but how can I use `exuberdata` to use critical values up to 2000? You mentioned it above, but I couldn't find it in docs.

**Comment by kvasilopoulos** [comment]
First, you have to install it through:
```
library(exuber)
install_exuberdata()
```
Then you can use it explicitly by:
```
library(exuberdata)
my_cv  <- radf_crit2[[no_of_obs_goes_here]]
```
Or implicitly by using the methods `summary`, `diagnostics`, `datestamp` or `autoplot` on series that exceed the 600 observations and leave the `cv` argument blank.
