### ISSUE TITLE
Optimal number of lags

### ISSUE THREAD

**Issue by MislavSag** [kvasilopoulos/exuber#13]
I am comparing `exuber` and `psymonitor` packages. In `psymonitor` they have IC, which control for lag lengths in ADF test. Does the exuber function `radf` choose optimal number of lags by default or it doesnt control the number of lags by AIC or BIC criterion?

**Comment by kvasilopoulos** [comment]
Hi @MislavSag,

No, intentionally we don't want to have this option in the packages. The recommendation in PSY(2015) p. 1058 is the following:

> Overall, size is reasonably well controlled when a small fixed lag length is used in the recursive
tests. This approach is therefore recommended for empirical use of the SADF and GSADF test
procedures as well as the dating algorithms that are implemented in the application later in the
article. 

So, we don't want to add more complexity if there isn't a reason to do so!

**Comment by MislavSag** [comment]
So, it is recommended to use 'small fixed lag'. Should I try lags 1 to 5 and check which works best (best in sense of identifying bubbles/crises)? I suppose it depends on the frequency of the data.

**Comment by kvasilopoulos** [comment]
Sure, if you need to. I would choose lag = 1 for most of the cases though.

**Comment by MislavSag** [comment]
Thanks on info!

**Comment by kvasilopoulos** [comment]
You are welcome!
