### ISSUE TITLE
New bubble tests

### ISSUE THREAD

**Issue by MislavSag** [kvasilopoulos/exuber#16]
Hi,

Do you plan to add new bubble tests into your package?

I have found several other approaches that are not implemented.
For example, very popular is lppls model (https://github.com/Boulder-Investment-Technologies/lppls).

I can try to implement by myself and make PR if you allow PR's.

**Comment by kvasilopoulos** [comment]
Hi @MislavSag,

For the time being, we are focused on stabilizing the API and complementing on the existing functionality (e.g. reverse datestamping etc). 

We also are planning to add more test in the future, but not at the moment. 

Thank you for your willingness, I will leave this issue open until we are ready to implement more.

**Comment by MislavSag** [comment]
@kvasilopoulos Thanks for feedback.

I will probably try to implement some of the other bubble tests in the future, so I will make PR when I finished.
