### ISSUE TITLE
x_breaks does not always work in plot.radf

### ISSUE THREAD

**Issue by s-spavound** [kvasilopoulos/exuber#2]
Tried using x_breaks = "20 years" for the S and P 500 Price-Dividend data as below:

test <- radf(ts(sp.500.ratio, start = c(1871, 1), frequency = 12))
crit <- mc_cv(1680, nrep = 10, parallel = T) #N.B. just 10 reps for speed
plot(test, crit, x_breaks = "20 years")

Fails with the following message:

Error in del/by : non-numeric argument to binary operator

**Comment by kvasilopoulos** [comment]
The problem is with ts objects, we cannot parse the date properly unless the user passes extra arguments. In the end, we just extract time() from the ts. So, I think we should get rid of ts completely. Matrix and data.frame as input is sufficient enough!

**Comment by s-spavound** [comment]
I have half a fix in the works to make it work properly. Will put it up and you can see whether you like it.

**Comment by kvasilopoulos** [comment]
Fixed it  at abbdf4a and then a minor adjustment at a26f5e8
