### ISSUE TITLE
warnings with radf_mc_cv

### ISSUE THREAD

**Issue by amarnp85** [kvasilopoulos/exuber#20]
I am getting the following warming when I run this command

sub_mc_cv <- radf_mc_cv(100, minw = 20)

tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
Warning message:
In system2("tput", "cols", stdout = TRUE) :
  running command ''tput' cols' had status 2
Warning message:
In system2("tput", "cols", stdout = TRUE) :
  running command ''tput' cols' had status 2

Do I need to be concerned about this?

**Comment by kvasilopoulos** [comment]
I don't think so, probably has something to do with the progress bar. Can you please try disabling the progress bar and try again:

```
library(exuber)
options("exuber.show_progress" = FALSE)
radf_mc_cv(100, 20)
```

**Comment by amarnp85** [comment]
I tried that and unfortunately not. The warning still shows. Any idea what it means?

**Comment by kvasilopoulos** [comment]
`tput` is a command that manipulates the terminal - changes colour of text, makes bold etc. Probably has nothing to do with exuber. Any problem with the results?

**Comment by amarnp85** [comment]
No the results seem to be in order. So not an issue with exuber - Fab package by the way,  thanks.
