### ISSUE TITLE
Mat size problem

### ISSUE THREAD

**Issue by Plak4ever** [kvasilopoulos/exuber#22]
I am trying to run the panel version of the test on a very large panel of 260 observations over 431 cros-sections (entities) and get the following error

Error in rls_gsadf(yxmat, min_win = minw, lag = lag) : 
  Mat::init(): requested size is too large; suggest to enable ARMA_64BIT_WORD

any workaround?

**Comment by kvasilopoulos** [comment]
Hi @Plak4ever,

We have never encountered this big of a matrix before, so it is probably outside the limits of Armadillo.

Can you please provide a reproducible example in order for me to have a look?
