### ISSUE TITLE
Issue with datestamp & autoplot function

### ISSUE THREAD

**Issue by sonjaoff** [kvasilopoulos/exuber#8]
Hi Kostas,

I've just updated to the new version of exuber (0.4.1), previously I used 0.3.0. Thank you for updating it, I think the changes and additions are really helpful. 

Unfortunately, I ran into an issue and I was wondering whether you can help me out here. I am relatively new to R, but my impression is that it has something to do with the augment_join function. Basically, I get the same error when using datestamp, autoplot & augment_join. 
I prepared an example using your example on the first page (leaving out summary to make it brief).
![Rplot03](https://user-images.githubusercontent.com/61694800/82759322-0383ca00-9ded-11ea-9dac-a52b50e20a7c.png)
I tried it with my own data, the EUStocksMarket, own simulated critical values and the stored ones, all with the same results.

Please let know, if you need any further information from me. 

Thanks a lot. 

Cheers,
Sonja

**Comment by kvasilopoulos** [comment]
Hi Sonja,

I cannot replicate the issue you are having. I suspect that there may be a problem with the version of some dependencies. Can you restart the session, remove and reinstall **tidyselect** and **dplyr**.

```r
remove.packages("tidyselect")
install.packages("tidyselect")

remove.packages("dplyr")
install.packages("dplyr")
```

Also, it would be great if you can append the `session_info()`.

**Comment by sonjaoff** [comment]
Hi Kostas,

great news! I removed and reinstalled **tidyselect** and **dplyr** and it worked! Thanks so much! I really appreciate it. I'll make sure to append the `session_info()` next time!
