### ISSUE TITLE
can't run radf_mc_cv function

### ISSUE THREAD

**Issue by lori99-data** [kvasilopoulos/exuber#9]
I was gonna to run cv <- radf_mc_cv(n = 792)
but always get this error:

Error in makePSOCKcluster(names = spec, ...) : 
  Cluster setup failed. 7 of 7 workers failed to connect.

Thanks for any advice to solve it.

**Comment by kvasilopoulos** [comment]
Hi, it seems like there is some issue with the `parallel` package that is not reproducible. You can try disabling the parallel option and run again:

```
library(exuber)
options(exuber.parallel = FALSE)
cv <- radf_mc_cv(n = 792)
```

Alternatively, if you are using the proposed minimum window (as in this case) you can use the stored critical values that exist in `exuberdata`:

```
library(exuber)
install_exuberdata()
cv <- exuberdata::radf_crit2[[792]]
```

**Comment by lori99-data** [comment]
It works. Thank you. much appreciated!
